### ISSUE TITLE
Bundle up CSS files

### ISSUE THREAD

**Issue by raerpo** [Draaakos/Skiff#13]
In index.hbs you are loading 9 individual CSS files. It can be improved adding an extra step in the webpack configuration to have only one optimize bundled file. 

I can help with a PR in this matter if you want.   

_Sent from my Xiaomi Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Draaakos** [comment]
ok, i can created the PR for you

**Comment by Draaakos** [comment]
and... if you want, you may create a new branch and i can merge it.
